# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3e86242efdaffda3ba7aafd2a7ac9c495e03c4fc9b22a2f0f6219dc43746fe83c8722c5722a0f66a909974913b98df4ce3f3b5fc32e111d1e146d3c1d8eb5b1

test:
  secret_key_base: 07c385e5c0ab7c307bdb8fe51afb9d8aceb7949f19d8c57f24545e9ba46f0d4266fe890992005538be840d751ae301e6842ae87426f0f8869095f4ce5bccec2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
